version: '3.4'

services:
  app:
    container_name: sandbox-rust-torch
    image: ${DOCKER_REGISTRY-}sandboxrusttorch
    # ports:
      # - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile